import Head from "next/head";

import Button from "../elements/baseButton";
import Form from "../components/form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button color="primary" bg="secondary">
          Everyone's Invited
        </Button>
        <Form />
      </main>
    </div>
  );
}
