import Head from 'next/head';
import { useRouter } from 'next/router';

import Button from '../elements/baseButton';
import Form from '../components/form';

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button type="button" onClick={() => router.push('/ReadTestimonies')}>
          Click me
        </button>
        <Form />
      </main>
    </div>
  );
}
