import Head from 'next/head';

import Masonry from './Masonry';
import Card from './Card';

// TODO: Need to fetch `posts` (by calling some API endpoint)
//       before this page can be pre-rendered.

export default function Testimonies() {
  return (
    <div>
      <Head>
        <title>Testimonies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Masonry columns={3}>
          {testimonies.map(testimony => (
            <Card key={testimony} title={testimony.Location} comment={testimony.Testimony}/>
          ))}
        </Masonry> */}
      </main>
    </div>
  );
}
