import Head from 'next/head';

// TODO: Need to fetch `posts` (by calling some API endpoint)
//       before this page can be pre-rendered.

export default function Testimonies() {
  return (
    <div>
      <Head>
        <title>Testimonies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {posts.map(post => (
            <li>{post.title}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}
